CREATE TABLE PlexData
				 (library_id            INT NOT NULL,
				  library_name          VARCHAR(50) NOT NULL,
				  show_id               INT NULL,
				  show_name             NVARCHAR(200) NULL,
				  season_number         INT NULL,
				  music_album           NVARCHAR(200) NULL,
				  season_studio         NVARCHAR(200) NULL,
				  episode_number        INT NULL,
				  show_rating           DECIMAL(5, 2) NULL,
				  show_content_rating   VARCHAR(10) NULL,
				  show_collection       VARCHAR(50) NULL,
				  episode_id            INT NOT NULL,
				  episode_name          NVARCHAR(200) NULL,
				  episode_duration      INT NULL,
				  episode_width         INT NULL,
				  episode_height        INT NULL,
				  episode_size          INT NULL,
				  episode_fps           DECIMAL(5, 2) NULL,
				  episode_video_codec   VARCHAR(25) NULL,
				  episode_audio_codec   VARCHAR(25) NULL,
				  episode_release_date  BIGINT NULL,
				  episode_added_date    BIGINT NULL,
				  movie_critic_rating   DECIMAL(5, 2) NULL,
				  movie_audience_rating DECIMAL(5, 2) NULL,
				  movie_content_rating  VARCHAR(25) NULL,
				  movie_collection      VARCHAR(50) NULL,
				  file_path             NVARCHAR(200) NULL,
				  file_type             VARCHAR(10) NULL);
GO